# Generated by rebar3_nix
let fetchOnly = { src, ... }: src;
in { builder ? fetchOnly, fetchHex, fetchFromGitHub }: rec {
  unicode_util_compat = builder {
    name = "unicode_util_compat";
    version = "0.7.0";
    src = fetchHex {
      pkg = "unicode_util_compat";
      version = "0.7.0";
      sha256 = "sha256-Je7m1n32GWDPanlCOVZlmbCeF+Zo03ACR7xJhjgVJSE=";
    };
    beamDeps = [ ];
  };
  quickrand = builder {
    name = "quickrand";
    version = "2.0.1";
    src = fetchHex {
      pkg = "quickrand";
      version = "2.0.1";
      sha256 = "sha256-FNtn1K72uIFYEOyfPM714yS3O1bK42h/mddSuFvdTJY=";
    };
    beamDeps = [ ];
  };
  hut = builder {
    name = "hut";
    version = "1.3.0";
    src = fetchHex {
      pkg = "hut";
      version = "1.3.0";
      sha256 = "sha256-fhXShVXYofK1o6kx7BIK8HU+SFOkxmBT2zVPNb+atWM=";
    };
    beamDeps = [ ];
  };
  cowlib = builder {
    name = "cowlib";
    version = "2.9.1";
    src = fetchHex {
      pkg = "cowlib";
      version = "2.9.1";
      sha256 = "sha256-5BddwkCnDZlhVhYIkeHGIjjt4XKeRXQL3TgGTa1HYXA=";
    };
    beamDeps = [ ];
  };
  cf = builder {
    name = "cf";
    version = "0.3.1";
    src = fetchHex {
      pkg = "cf";
      version = "0.3.1";
      sha256 = "sha256-MV6NRH06SwK82/o5etA7u5iKbgqm9E063Q9OPDv5dnI=";
    };
    beamDeps = [ ];
  };
  zipper = builder {
    name = "zipper";
    version = "1.0.1";
    src = fetchHex {
      pkg = "zipper";
      version = "1.0.1";
      sha256 = "sha256-ah/T4fDMHR31ZCyaDOIXgDZBGwpclkKFHR2idr1zfC0=";
    };
    beamDeps = [ ];
  };
  yamerl = builder {
    name = "yamerl";
    version = "0.8.1";
    src = fetchHex {
      pkg = "yamerl";
      version = "0.8.1";
      sha256 = "sha256-lssw+dZDRP7Q74qS6fFvIH3mwE3/9PNmdSynn1vOsj8=";
    };
    beamDeps = [ ];
  };
  uuid_erl = builder {
    name = "uuid_erl";
    version = "2.0.1";
    src = fetchHex {
      pkg = "uuid_erl";
      version = "2.0.1";
      sha256 = "sha256-q1fKzNUfFwAR5fREzoZfhLQWBeSDqe/MRowa+uyHVTs=";
    };
    beamDeps = [ quickrand ];
  };
  supervisor3 = builder {
    name = "supervisor3";
    version = "1.1.11";
    src = fetchHex {
      pkg = "supervisor3";
      version = "1.1.11";
      sha256 = "sha256-5sLe28q8uiSZWiGKyhLbXiCLgNMlJpKyLvDxomYQS1A=";
    };
    beamDeps = [ ];
  };
  ssl_verify_fun = builder {
    name = "ssl_verify_fun";
    version = "1.1.6";
    src = fetchHex {
      pkg = "ssl_verify_fun";
      version = "1.1.6";
      sha256 = "sha256-vbDSRx9FPIj/OQjnaG+G+b4yfQZcwewW+kVAGX6gRoA=";
    };
    beamDeps = [ ];
  };
  snappyer = builder {
    name = "snappyer";
    version = "1.2.8";
    src = fetchHex {
      pkg = "snappyer";
      version = "1.2.8";
      sha256 = "sha256-NVGOeaKFSLVtj9au4vVl8S9RwtPQU/nPqBfIO+iMTz0=";
    };
    beamDeps = [ ];
  };
  recon = builder {
    name = "recon";
    version = "2.5.1";
    src = fetchHex {
      pkg = "recon";
      version = "2.5.1";
      sha256 = "sha256-VyHGttUBItj2jMyscSyqEjH5eJS6t3nv9f8PiGy0Rkg=";
    };
    beamDeps = [ ];
  };
  ranch = builder {
    name = "ranch";
    version = "2.0.0";
    src = fetchHex {
      pkg = "ranch";
      version = "2.0.0";
      sha256 = "sha256-wgpIQMfWYjwZgS06fIKLLxvRU+8PEky2nFT+UdikKuA=";
    };
    beamDeps = [ ];
  };
  prometheus = builder {
    name = "prometheus";
    version = "4.8.0";
    src = fetchHex {
      pkg = "prometheus";
      version = "4.8.0";
      sha256 = "sha256-D8LhcQMHPts3WKRqXUSwBhkb8ltzy6ord5EJ3jlq/LU=";
    };
    beamDeps = [ ];
  };
  poolboy = builder {
    name = "poolboy";
    version = "1.5.2";
    src = fetchHex {
      pkg = "poolboy";
      version = "1.5.2";
      sha256 = "sha256-2teXBM5UQPPVo2gchZC53CXRpWHo9anJlSgQEoYJAeM=";
    };
    beamDeps = [ ];
  };
  parse_trans = builder {
    name = "parse_trans";
    version = "3.4.0";
    src = fetchHex {
      pkg = "parse_trans";
      version = "3.4.0";
      sha256 = "sha256-+Z42iDC+pEVSIk434ElDpUh08IuFkEhd6NE4MrY6LcM=";
    };
    beamDeps = [ ];
  };
  mimerl = builder {
    name = "mimerl";
    version = "1.2.0";
    src = fetchHex {
      pkg = "mimerl";
      version = "1.2.0";
      sha256 = "sha256-8nhYVlCqWBmGJkY46/aY+LsZ3yl/Zq2RsYkQ38bhkyM=";
    };
    beamDeps = [ ];
  };
  metrics = builder {
    name = "metrics";
    version = "2.5.0";
    src = fetchHex {
      pkg = "metrics";
      version = "2.5.0";
      sha256 = "sha256-rgYZOMjDvel9F76aeStj4VweHv/hZZirh6YjhPXzcUs=";
    };
    beamDeps = [ ];
  };
  meck = builder {
    name = "meck";
    version = "0.9.2";
    src = fetchHex {
      pkg = "meck";
      version = "0.9.2";
      sha256 = "sha256-gTRPVhNX3ECoNEr6U3Z8MmaRUzVbYm6p/LyNprMEWCY=";
    };
    beamDeps = [ ];
  };
  lager = builder {
    name = "lager";
    version = "3.9.2";
    src = fetchHex {
      pkg = "lager";
      version = "3.9.2";
      sha256 = "sha256-f5BNnoeoy35mFW7TF2jRyOJuuh1U9LyFsapKwfY0DCg=";
    };
    beamDeps = [ goldrush ];
  };
  katana_code = builder {
    name = "katana_code";
    version = "1.1.2";
    src = fetchHex {
      pkg = "katana_code";
      version = "1.1.2";
      sha256 = "sha256-5+YWKkToJqA/aLUDt9kpgbiUv4NMHvDmR3g/fWaIAhw=";
    };
    beamDeps = [ ];
  };
  kafka_protocol = builder {
    name = "kafka_protocol";
    version = "3.0.1";
    src = fetchHex {
      pkg = "kafka_protocol";
      version = "3.0.1";
      sha256 = "sha256-x3okAFNwcurxj+ghxvRpyHl4jyFcYGEqoOqjRE3d9Gc=";
    };
    beamDeps = [ crc32cer snappyer ];
  };
  jsx = builder {
    name = "jsx";
    version = "3.0.0";
    src = fetchHex {
      pkg = "jsx";
      version = "3.0.0";
      sha256 = "sha256-N77KBDX1yoovRfdqRiEedkGPvvgMNvA2HCSfx1BZ3G0=";
    };
    beamDeps = [ ];
  };
  jsone = builder {
    name = "jsone";
    version = "1.5.7";
    src = fetchHex {
      pkg = "jsone";
      version = "1.5.7";
      sha256 = "sha256-XxRsv5U0aWZ+7hRfsGbW7mubGBvP1UcpUxdSbnRk1zI=";
    };
    beamDeps = [ ];
  };
  jose = builder {
    name = "jose";
    version = "1.11.1";
    src = fetchHex {
      pkg = "jose";
      version = "1.11.1";
      sha256 = "sha256-B49sn7PNL0z6/JcsgUJhp9Ho0rNoXAp264fhWO//GsU=";
    };
    beamDeps = [ ];
  };
  jiffy = builder {
    name = "jiffy";
    version = "1.0.8";
    src = fetchHex {
      pkg = "jiffy";
      version = "1.0.8";
      sha256 = "sha256-+a6Ya6WghU60jPanYZLZNnCG2obCAZfaQwYwvnwIek4=";
    };
    beamDeps = [ ];
  };
  idna = builder {
    name = "idna";
    version = "6.1.1";
    src = fetchHex {
      pkg = "idna";
      version = "6.1.1";
      sha256 = "sha256-kjdut4lEEu0ZrEdeSob3tBPBufu1vRbczVeTQVeUTOo=";
    };
    beamDeps = [ unicode_util_compat ];
  };
  ibrowse = builder {
    name = "ibrowse";
    version = "4.4.1";
    src = fetchHex {
      pkg = "ibrowse";
      version = "4.4.1";
      sha256 = "sha256-HobFkdvG0nBjJiVTSYa+yjCBOvfOeE50Ll/DjjQsKbM=";
    };
    beamDeps = [ ];
  };
  hackney = builder {
    name = "hackney";
    version = "1.17.4";
    src = fetchHex {
      pkg = "hackney";
      version = "1.17.4";
      sha256 = "sha256-3hb/SZZVbIVI1RL02+It1YpYe/MzLn/TYkMKfvOYaxY=";
    };
    beamDeps = [ certifi idna metrics mimerl parse_trans ssl_verify_fun unicode_util_compat ];
  };
  gun = builder {
    name = "gun";
    version = "1.3.3";
    src = fetchHex {
      pkg = "gun";
      version = "1.3.3";
      sha256 = "sha256-MQbOFn+clyP4SeT7VOpKTYFOOZauJDocgoslbnSQQeA=";
    };
    beamDeps = [ cowlib ];
  };
  grpc_gun = builder {
    name = "grpc_gun";
    version = "2.0.0";
    src = fetchHex {
      pkg = "grpc_gun";
      version = "2.0.0";
      sha256 = "sha256-A9u8oanGBKAmekDqHWmYYiUJGsuCLeCy2+oh1YFeQQs=";
    };
    beamDeps = [ cowlib ];
  };
  goldrush = builder {
    name = "goldrush";
    version = "0.1.9";
    src = fetchHex {
      pkg = "goldrush";
      version = "0.1.9";
      sha256 = "sha256-mctBKM/8syJ1geXU2APVQT+mQ/TrllI/d9nmk32ZTOs=";
    };
    beamDeps = [ ];
  };
  getopt = builder {
    name = "getopt";
    version = "1.0.2";
    src = fetchHex {
      pkg = "getopt";
      version = "1.0.2";
      sha256 = "sha256-oAKa6kMi+4KmH2h2ptnGbcmHi2y2H6oT3zGHOE/U6iY=";
    };
    beamDeps = [ ];
  };
  gen_smtp = builder {
    name = "gen_smtp";
    version = "1.1.1";
    src = fetchHex {
      pkg = "gen_smtp";
      version = "1.1.1";
      sha256 = "sha256-UbxQzAF+/UpCSMvDnqMPtg76fUpJaImG+vrYRDT/mrc=";
    };
    beamDeps = [ hut ranch ];
  };
  erlware_commons = builder {
    name = "erlware_commons";
    version = "1.4.0";
    src = fetchHex {
      pkg = "erlware_commons";
      version = "1.4.0";
      sha256 = "sha256-GF7PXPQ7qzoBPds2FM57un9seoJ5BOZOV9pU/N/c4uY=";
    };
    beamDeps = [ cf ];
  };
  erlsom = builder {
    name = "erlsom";
    version = "1.5.0";
    src = fetchHex {
      pkg = "erlsom";
      version = "1.5.0";
      sha256 = "sha256-Vanb+c+nf8/BCL2OLE+feE3qIoqPSwbqELaElElGlVo=";
    };
    beamDeps = [ ];
  };
  erlexec = builder {
    name = "erlexec";
    version = "1.18.11";
    src = fetchHex {
      pkg = "erlexec";
      version = "1.18.11";
      sha256 = "sha256-K6ko8b33TgmMQTRl8QnBC10eE1lWjre/TJn5GsmDuP8=";
    };
    beamDeps = [ ];
  };
  epgsql = builder {
    name = "epgsql";
    version = "4.5.0";
    src = fetchHex {
      pkg = "epgsql";
      version = "4.5.0";
      sha256 = "sha256-CgLTOMwUJsWHO0Ev7Z1pT3tRQ5M8X4XyRGVaXneyMHg=";
    };
    beamDeps = [ ];
  };
  elvis_core = builder {
    name = "elvis_core";
    version = "1.1.2";
    src = fetchHex {
      pkg = "elvis_core";
      version = "1.1.2";
      sha256 = "sha256-xO5Cp6fC/FZ/Pqa1FQFkzWgpDxEA6bGaTPiG2Kocpzw=";
    };
    beamDeps = [ katana_code zipper ];
  };
  credentials_obfuscation = builder {
    name = "credentials_obfuscation";
    version = "2.4.0";
    src = fetchHex {
      pkg = "credentials_obfuscation";
      version = "2.4.0";
      sha256 = "sha256-0oqJgw4waYsHXemk2+aDogaFxr7R47ffdEoMBub/IAo=";
    };
    beamDeps = [ ];
  };
  crc32cer = builder {
    name = "crc32cer";
    version = "0.1.10";
    src = fetchHex {
      pkg = "crc32cer";
      version = "0.1.10";
      sha256 = "sha256-Wx9H79ChtLdBHx814U08jG2m5qKnJeyPLPGrE3A+Xzg=";
    };
    beamDeps = [ ];
  };
  cowboy = builder {
    name = "cowboy";
    version = "2.8.0";
    src = fetchHex {
      pkg = "cowboy";
      version = "2.8.0";
      sha256 = "sha256-RkPk+6dKyW1NFSx1gD3m+tCz+l3zVMca/dbL7rFfrIo=";
    };
    beamDeps = [ cowlib ranch ];
  };
  coveralls = builder {
    name = "coveralls";
    version = "2.2.0";
    src = fetchHex {
      pkg = "coveralls";
      version = "2.2.0";
      sha256 = "sha256-zVTbCqjGS1OSgBicVhns7hOkaiiw8ct3RUTdzBZiBKM=";
    };
    beamDeps = [ jsx ];
  };
  certifi = builder {
    name = "certifi";
    version = "2.6.1";
    src = fetchHex {
      pkg = "certifi";
      version = "2.6.1";
      sha256 = "sha256-UkyXtJkbOEndXBemMSI4licsawr0RneLpGdaHf9Tu34=";
    };
    beamDeps = [ ];
  };
  brod = builder {
    name = "brod";
    version = "3.15.5";
    src = fetchHex {
      pkg = "brod";
      version = "3.15.5";
      sha256 = "sha256-xTfCrjBmre5CEaUVS8Yav210MoZ3mid0D3qaxwDSjtM=";
    };
    beamDeps = [ kafka_protocol supervisor3 ];
  };
  bear = builder {
    name = "bear";
    version = "1.0.0";
    src = fetchHex {
      pkg = "bear";
      version = "1.0.0";
      sha256 = "sha256-FXtnkBrfhP8NpurgNcoSkqCsGKpVFIFU2MWCssaJWds=";
    };
    beamDeps = [ ];
  };
  bbmustache = builder {
    name = "bbmustache";
    version = "1.11.0";
    src = fetchHex {
      pkg = "bbmustache";
      version = "1.11.0";
      sha256 = "sha256-fJzc9Y3AQzd6t5KoxxCdiQJpX8rjs1wQeKizjdz4bl8=";
    };
    beamDeps = [ ];
  };
  base64url = builder {
    name = "base64url";
    version = "1.0.1";
    src = fetchHex {
      pkg = "base64url";
      version = "1.0.1";
      sha256 = "sha256-+bOt1HMaAqmwQQOYtHWzPnVmppU2Ujemve4btEdxn1w=";
    };
    beamDeps = [ ];
  };
  accept = builder {
    name = "accept";
    version = "0.3.5";
    src = fetchHex {
      pkg = "accept";
      version = "0.3.5";
      sha256 = "sha256-EbGMIgvMLqtjtUcMA47xDrZ4O8sfzbEapBN976WsG7g=";
    };
    beamDeps = [ ];
  };
}
